### ISSUE TITLE
MF function calculate wrong Molecular formula when importing sdf files from drugbank.ca

### ISSUE THREAD

**Issue by boloson** [girke-lab/ChemmineR#1]
Hi,

I downloaded sdf files from https://www.drugbank.ca/releases/5-0-7/downloads/approved-structures.

when I do the following 

sdf_set <- read.SDFset("drugbank_approved_structures.sdf")
head(MF(sdf_set))

the output is 
           CMP1            CMP2            CMP3            CMP4            CMP5            CMP6 
  "C9800N24O33"   "C5900N18O14" "C4600N14O12S2" "C7000ClN17O14"   "C7200N17O26"   "C6200N11O12" 

The Hydrogen number is not shown, but when using the  sdfsample dataset, the hydrogen is generated correctly. Is the problem with the sdf file from Drugbank or a bug ?

**Comment by tgirke** [comment]
Set `addH=TRUE`. The help file `?MF` provides more detail.
