### ISSUE TITLE
Adding additional functional groups to groups function

### ISSUE THREAD

**Issue by KristinaRiemer** [girke-lab/ChemmineR#10]
Hi all! Thank you so much for creating and maintaining this R package! I'm working with [Laura Meredith's group](http://www.laurameredith.com/?page_id=703) at the University of Arizona on a project calculating volatility of various soil compounds. I'm helping them automate this volatility pipeline, and this package has been indispensable for counting compound atoms and functional groups. 

We are using `ChemmineR::groups` to count functional groups. There are some functional groups that need to be counted for volatility that aren't currently included in that function, so I was hoping to get some help in adding those? I know functional groups are added in the code [here](https://github.com/girke-lab/ChemmineR/blob/db24d96f2d534dd85ba50db61b615d8560621d6d/R/AllClasses.R#L2098) using some regular expressions. Because I'm not a chemist and also not familiar enough with the format of mol files or how they're read in as SDFset containers, I am possibly looking for some guidance in how to write the regular expressions for the functional groups we're interested in. A list of them is below: 

- Nitrates NO3
- Phenols (OH on aromatic ring)
- Alicyclic ether
- Aromatic amine rings

I can imagine some of these might be difficult or impossible to create reg exs for, and also I might need to get more information from @laurameredith and her group about what they're looking for. Thank you so much for any help you can offer!

**Comment by tgirke** [comment]
For this you may want to use SMARTS strings supported in `ChemmineR` via the companion `ChemmineOB` package for OpenBabel support (some examples are [here](https://www.bioconductor.org/packages/release/bioc/vignettes/ChemmineR/inst/doc/ChemmineR.html#OpenBabel_Functions)). The function to use here is called `smartsSearchOB`. In fact most/all and more of what you get via the `groups` function you can generate via SMARTS queries. The latter was implemented in `ChemmineR` after we added `ChemmineOB`. Useful examples to get you started with SMART strings are provided on [this](https://www.daylight.com/dayhtml_tutorials/languages/smarts/smarts_examples.html) Daylight page.  For instance, for finding hydroxy groups and phenols in a set of compounds stored as an `SDFset` you do:

```r
library(ChemmineR); library(ChemmineOB)
data(sdfsample)
groupDF <- data.frame(
                   hydroxy=smartsSearchOB(sdfsample,"[OX2H]", uniqueMatches=FALSE),
                   phenol=smartsSearchOB(sdfsample, "[OX2H][cX3]:[c]", uniqueMatches=FALSE)
)
head(groupDF)
```

**Comment by KristinaRiemer** [comment]
Gotcha, thanks for the quick response and suggested redirection! I'll check this out.
