### ISSUE TITLE
Way to capture OpenBabel warning messages?

### ISSUE THREAD

**Issue by Aariq** [girke-lab/ChemmineR#14]
I'm trying to write some tests that should error if there are OpenBabel warnings like the following:

```
>   x <- ChemmineR::propOB(sdf)
==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: The Chiral Flag should be either 0 or 1. The value of 4294967285 will be ignored.

==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: Problems reading the Count line of an MDL file
There may be erroneous addition spaces or
the file may contains Atom Lists, which are ignored

```

But these messages don't seem to be captured by `sink()` or `capture.output()`.  I'm hoping you might know a way to capture these warnings in an R object or file since you are likely more familiar than me with where they are coming from.

**Comment by Aariq** [comment]
FYI I ended up solving this (with the help of @gaborcsardi again) with the following helper function:

``` r
really_capture_error <- function(expr) {
  tmp <- tempfile()
  on.exit(unlink(tmp), add = TRUE)
  orig <- processx::conn_set_stderr(
    processx::conn_create_file(tmp, write = TRUE),
    drop = FALSE
  )
  on.exit(processx::conn_set_stderr(orig), add = TRUE)
  expr
  stderr <- readLines(tmp)
  if(length(stderr) != 0) {
    stop(stderr)
  }
}

```

`really_capture_error(ChemmineR::propOB( <a malformed SDFset object> ))` converts the OpenBabel error into an actual R error that can be captured in tests.  For example, using `testthat`: 

``` r
test_that(".mol files are correctly formed", {
  skip_on_cran()
  skip_on_os("windows") # really_capture_error() errors on windows
  sdf <- ChemmineR::read.SDFset("path/to/compound.mol")
  expect_no_error(
    really_capture_error(x <- ChemmineR::propOB(sdf))
  )
  
})
```

This is a "very nasty trick", and also seems to error on windows in its current form.  Best run in an isolated environment, e.g. using `callr::r()`

**Comment by gaborcsardi** [comment]
> This is a "very nasty trick", and also seems to error on windows in its current form. Best run in an isolated environment, e.g. using `callr::r()`

Sorry, what I meant was that if you use `callr::r()` then you do not need this trick at all.

**Comment by Aariq** [comment]
Ah, sorry.  I think I understand now.  I couldn't manage to capture the error with `callr::r()` so I ended up going with the "nasty trick" for now at least.

**Comment by gaborcsardi** [comment]
It goes like this:
```r
out <- tempfile()
err <- tempfile()
callr::r(function() system(">&2 echo error"), stdout = out, stderr = err)
#> 0

readLines(out)
#> character(0)

readLines(err)
#> [1] "error"
```
