### ISSUE TITLE
Outdated error message in `.ensureOB()` ?

### ISSUE THREAD

**Issue by Aariq** [girke-lab/ChemmineR#17]
https://github.com/girke-lab/ChemmineR/blob/f362c577eabb049b59361ee61ca924cf013b2b3a/R/sim.R#L582-L587

The error message printed by `.ensureOB()` says that `ChemmineOB` isn't available for windows, but I don't think that is the case (there is a windows binary here: https://www.bioconductor.org/packages/2.14/bioc/bin/windows/contrib/3.1/ChemmineOB_1.2.9.zip)

Interestingly, I noticed this error message on a failing r-universe build on macOS where `OpenBabel` isn't installed, but `ChemmineOB` I think _is_ installed, so this function might not be doing what you think it's doing. https://github.com/r-universe/cct-datascience/actions/runs/6354874446/job/17569286604

**Comment by khoran** [comment]
fixed that message.
