### ISSUE TITLE
Formaldehyde not counted as RCHO group

### ISSUE THREAD

**Issue by Aariq** [girke-lab/ChemmineR#20]
Formaldehyde isn't counted as an aldehyde by `groups()`

``` r
library(ChemmineR)
sdf <- smiles2sdf(c("formaldehyde" = "C=O"))
groups(sdf)
#>  RNH2  R2NH   R3N ROPO3   ROH  RCHO  RCOR RCOOH RCOOR   ROR  RCCH   RCN 
#>     0     0     0     0     0     0     0     0     0     0     0     0
```

<sup>Created on 2023-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by tgirke** [comment]
It lacks the R. To have a RCHO match, R needs to be at least a heavy atom.

**Comment by Aariq** [comment]
Got it!  Just wanted to make sure this was intentional!
