### ISSUE TITLE
Add plotStruc output as dendrogram labels

### ISSUE THREAD

**Issue by urwa** [girke-lab/ChemmineR#3]
I am reading in an SDF dataset, running the FMCS algorithm on it then plotting the output matrix as a dendrogram. This works fine. 

But I am looking to use compounds structure [ the output of plotStruc ] as the labels of the dendrogram instead of plain text names.  I am failing at this.

The output of plotStruc cannot be stored in a variable since its a plot and return value is NULL.
I tried saving the compound structures as png files but dendrogram is not taking it as labels.

Does this package provide any assistance in doing what I am trying to do?

`#process`
`sdfset <- read.SDFset("INPUT.sdf")` 
`apset <- sdf2ap(sdfset) # Generate atom pair descriptor database for searching`

`#crunch data into matrix for dendrogram`
 ` sdf <- sdfset`
 ` sdf@ID <- sdfid(sdf)`
  `library(doParallel)`
  `num_procs <- detectCores()`
  `d <- sapply(cid(sdf), function(x) fmcsBatch(sdf[x], sdf, au=0, bu=0, matching.mode="aromatic", numParallel=num_procs)[,"Overlap_Coefficient"])`
  `# d <- sapply(cid(sdf), function(x) fmcsBatch(sdf[x], sdf, au=0, bu=0, matching.mode="aromatic")[,"Overlap_Coefficient"])`
 
`#make the dendrogram`
`hc <- hclust(as.dist(1-d), method="complete")`
`hc_den <- as.dendrogram(hc)`

`# saving compound structures as png files`
`for (i in 1:length(sdf)){`
 ` png(paste0("img/",sdf[i]@ID,".png"), width=200, height=200)`
 ` plotStruc(sdf[[i]]) `
 ` dev.off()`
`}`

`# reading png files into an array`
`hc.label <- array(character())`
`for( i in length(sdf)){`
 ` hc.label[i] <- readPNG(paste0("img/",sdf[i]@ID,".png"))`
`}`

`# pdf - horizontal dendrogram`
`hc_hor <-  hc_hor %>%`
 ` set("branches_lwd", 1) %>% `
 ` set("labels_cex", 0.5) %>%`
  `set("labels",  hc.label)`
`pdf("hc_hor.pdf", width = 40, height = 70)`
`plot(hc_hor, horiz = TRUE)`
`dev.off()`

A related question I asked on StackOverflow is: 
https://stackoverflow.com/questions/51407786/r-dendrogram-add-images-to-nodes-labels

**Comment by tgirke** [comment]
That's is not something the package is supporting at this point. To develop your own custom solution, you might want to look into the ggtree package or ape: http://bit.ly/2zVsgPt
