### ISSUE TITLE
practical way to compare two SMILES structures

### ISSUE THREAD

**Issue by alperyilmaz** [girke-lab/ChemmineR#4]
Hi,
I'm trying to figure out a way to calculate Tanimoto similarity between to compounds. I have SMILES data for each (actually, I have a data frame two columns of which has SMILES data and I'd like to calculate similarity for each row)

here are two molecules
```R
library(ChemmineR)
# D-glucose
mol1 <- smiles2sdf("C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)O")
# D-glucose-6-phosphate
mol2 <- smiles2sdf("C([C@H]([C@H]([C@@H]([C@H](C=O)O)O)O)O)OP(=O)(O)O")
```
As far as I understand I need to follow this route: SMILES :arrow_forward: SDF :arrow_forward: AP :arrow_forward: Fingerprint (phew!)

This is the code I tried
```R
mol1ap <- sdf2ap(mol1)
mol2ap <- sdf2ap(mol2)

mol1fp <- desc2fp(x=mol1ap, descnames=1024, type="character")
# Error in `[<-`(`*tmp*`, i, descnames %in% as.character(apsetlist[[i]]),  : 
# subscript out of bounds
```
If `desc2fp` would have run correctly I was  planning to run the following lines to calculate the similarity

```R
mol2fp <- desc2fp(x=mol2ap, descnames=1024, type="character")
fpSim(mol1fp, mol2fp, method="Tanimoto")
```

I have two questions: (1) how can I troubleshoot `desc2fp` problem? (2) Am I on the right track, is there a shorter way to calculate similarity between two SMILES input?

**Comment by tgirke** [comment]
Most of the code is correct but at the beginning `smiles2sdf` requires named vectors. The following should work fine for your example.
```r
library(ChemmineR)                                                                                                                         
sdfset <- smiles2sdf(c(cmp1="C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)O",                                                                  
                     cmp2="C([C@H]([C@H]([C@@H]([C@H](C=O)O)O)O)O)OP(=O)(O)O"                                                              
                     ))                                                                                                                    
apset <- sdf2ap(sdfset)                                                                                                                    
fpset <- desc2fp(x=apset, descnames=512, type="FPset")                                                                                     
fpSim(fpset[1], fpset[2], method="Tanimoto")  
```
Since your real input is a tabular file, you can read it with `read.SMIset()`, but pay attention to the name component in the last column (see help file).

**Comment by alperyilmaz** [comment]
Thank you very much..

**Comment by alperyilmaz** [comment]
Thank you very much..
