### ISSUE TITLE
How to connect and use a dataframe with SMILES column with ChemmineR.

### ISSUE THREAD

**Issue by makis23** [girke-lab/ChemmineR#5]
I have a set of SMILES codes of different molecules and I would like to know how to determine similarity among them. I have decided to use the ChemmineR package based on this [tutorial][1]. The issue is that I cannot understand how to connect my dataframe and use it like a ChemmineR object in order to run the analysis on `SMILES`.

    DrugName<-c("alclofenac","alosetron")
    DrugID_CID<-c("30951","2099")
    DrugID<-c("CHEMBL94081","DB00969")
    DrugBank<-c("DB13167","DB00969")
    SMILES<-c("OC(=O)Cc1ccc(OCC=C)c(Cl)c1","Cc1[nH]cnc1CN1CCc2c(C1=O)c1ccccc1n2C")
    Target<-c("PTGS1","HTR3A")
    
    test<-data.frame(DrugName,DrugID_CID,DrugID,DrugBank,SMILES,Target)

I have used the `read.SMIset` function which imports one or many molecules from a SMILES file and stores them in a SMIset container but I cannot understand how to further proceed with this.

    library("ChemmineR")

    test; smiset <- smisample
    write.SMI(smiset, file="sub.smi") 
    smiset <- read.SMIset("sub.smi")
    
    data(smisample) # Loads the same SMIset provided by the library 
    smiset <- smisample
    smiset 
    
    view(smiset) 
    
    cid(smiset) 
    smi <- as.character(smiset)
    
      as(smi, "SMIset") 

  [1]: https://bioconductor.org/packages/release/bioc/vignettes/ChemmineR/inst/doc/ChemmineR.html

**Comment by tgirke** [comment]
You want to store your input smiles strings in a tabular file that you import with `read.SMIset`. For the exact format, read the help file for this function. After this you convert the `SMIset` to an `SDFset` with `smiles2sdf`. From there you follow the instructions for any of the analysis routines performed on `SDFsets` including structural similarity comparisons in this [section](https://bioconductor.org/packages/release/bioc/vignettes/ChemmineR/inst/doc/ChemmineR.html#similarity-comparisons-and-searching) of the manual you reference.

**Comment by makis23** [comment]
When I try to 
```
#store your input smiles strings in a tabular file that you import with read.SMIset
test; smiset <- test$SMILES
write.SMI(smiset, file="sub.smi") 
smiset <- read.SMIset("sub.smi")
```

I get:

```
Error in write.table(smima, file = file, quote = FALSE, sep = "\t", row.names = FALSE,  : 
  object 'smima' not found
```

Also if I load only the SMILES how will the connection with DrugName will be achieved?

**Comment by tgirke** [comment]
You error message relates to a command that is different from the one you are showing. It complains that `smima` doesn't exist. Custom name handling is best achieved on the `SDFset` level. Please try to go through the manual to learn how to use the package. Often it is best to work with the provided sample data set from the package and then adapt to your own data.

**Comment by makis23** [comment]
Yes I know that it comes from the write.SMI. Sorry but I do not get it. You mentioned that 'You want to store your input smiles strings in a tabular file that you import with read.SMIset.' as the first thing to do. In the tutorial you use smisample which is already in the proper form but there is nowhere how to convert a dataframe into this form in order to use read.SMIset afterwards.

**Comment by tgirke** [comment]
If you have it in a data.frame then the standard function you use in R is write.table with tab as column separator. This gives you the tab delimited file you would use as a starting point.

**Comment by makis23** [comment]
I would really appreciate your help with that. I do not know how to recreate a SMIset object similar to `smisample` that you use
```
DrugName<-c("alclofenac","alosetron")
SMILES<-c("OC(=O)Cc1ccc(OCC=C)c(Cl)c1","Cc1[nH]cnc1CN1CCc2c(C1=O)c1ccccc1n2C")
test2<-data.frame(DrugName,SMILES)
write.table(temp,"temp.sdf",sep = "/t")
sdfset <- read.SDFset("temp.sdf")
```

**Comment by xiaodfeng** [comment]
I come across similar problem. The following codes may be helpful to you:
## Construct sdfset
smiles<-DTSmi$SMILES
names(smiles)<-paste(DTSmi$MolecularFormula,DTSmi$Identifier)
Convert<-convertFormat("SMI","SDF",paste(paste(smiles,names(smiles),sep="\t"),collapse="\n"))
Strsplit<-strsplit(Convert,"\n",fixed=TRUE)
write.table(Strsplit,'Strsplit.txt',row.names=F,quote = F,sep = "\t") # for testing purpose
sdfset<-read.SDFset(unlist(Strsplit))

**Comment by julie732** [comment]
I think I am having the same problem. I have a .txt file that has my SMILES strings on separate lines and when I import it into R, it imports as a data.frame. How do I convert this to a SMIset? What is a SMILES file?

I can get everything to work using the example dataset but I cannot figure out how to apply it to my list of SMILES.

**Comment by tgirke** [comment]
The following examples how to import/export tabular smiles files and coercing them to a SMIset object should help. This includes direct creation of `SMIset` objects as well as from intermediate `data.frames` and `character` vectors.

**Basic SMILES import/export routine**                                                                                                                                                                                                                                                                                                                                                       
```
library(ChemmineR)                                                                                                                                                                                                                                                                                                                                                                          
data(smiset)                                                                                                                                                                                                                                                                                                                                                                                
data(smisample); smiset <- smisample                                                                                                                                                                                                                                                                                                                                                        
smiset                                                                                                                                                                                                                                                                                                                                                                                      
write.SMI(smiset[1:4], file="sub.smi")                                                                                                                                                                                                                                                                                                                                                      
(smiset <- read.SMIset("sub.smi")) # Has two columns separated by tab: smiles string and ID                                                                                                                                                                                                                                                                                                 
```                                                                                                                                                                                                                                                                                                                                                                                         
**SMILES from character vector**                                                                                                                                                                                                                                                                                                                                                             
```
(smichar <- as.character(smiset))                                                                                                                                                                                                                                                                                                                                                           
writeLines(smichar, "test.smi") # Creates smiles file with only one column (smiles string)                                                                                                                                                                                                                                                                                                  
(smiset <- read.SMIset("sub.smi"))                                                                                                                                                                                                                                                                                                                                                          
```                                                                                                                                                                                                                                                                                                                                                                                            
**Import as data.frame and then coerce to SMIset** 
Note: this uses old read.delim function. Consider using `readr` package instead.                                                                                                                                                                                                                                                                                                                                          
```
df <- read.delim("sub.smi", na.strings = "", fill=TRUE, header=FALSE, check.names=FALSE, sep="\t")                                                                                                                                                                                                                                                                                          
(smichar <- setNames(as.character(df[,1]), as.character(df[,2])))                                                                                                                                                                                                                                                                                                                           
(smiset <- as(smichar, "SMIset"))     
```
